# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /nfs/ug/homes-0/y/yusufal5/Desktop/ChorusFilterTester/axi4stream_vip_0_ex/axi4stream_vip_0_ex.srcs/sources_1/bd/ex_sim/ip/ex_sim_axi4stream_vip_passthrough_0/ex_sim_axi4stream_vip_passthrough_0.xci
# IP: The module: 'ex_sim_axi4stream_vip_passthrough_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /nfs/ug/homes-0/y/yusufal5/Desktop/ChorusFilterTester/axi4stream_vip_0_ex/axi4stream_vip_0_ex.srcs/sources_1/bd/ex_sim/ip/ex_sim_axi4stream_vip_passthrough_0/ex_sim_axi4stream_vip_passthrough_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ex_sim_axi4stream_vip_passthrough_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /nfs/ug/homes-0/y/yusufal5/Desktop/ChorusFilterTester/axi4stream_vip_0_ex/axi4stream_vip_0_ex.srcs/sources_1/bd/ex_sim/ip/ex_sim_axi4stream_vip_passthrough_0/ex_sim_axi4stream_vip_passthrough_0.xci
# IP: The module: 'ex_sim_axi4stream_vip_passthrough_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /nfs/ug/homes-0/y/yusufal5/Desktop/ChorusFilterTester/axi4stream_vip_0_ex/axi4stream_vip_0_ex.srcs/sources_1/bd/ex_sim/ip/ex_sim_axi4stream_vip_passthrough_0/ex_sim_axi4stream_vip_passthrough_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ex_sim_axi4stream_vip_passthrough_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
